### ISSUE TITLE
Enabling features in cluster subspaces is not working

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#112]
After adding cluster (bundle items) in [Simulation space](https://www.humanitarianresponse.info/en/operations/simulation-training/), there were no features in the horizontal menu like (Contacts, Documents, Maps), so I went to the Group->Features, and enables the features but it didn't work.
@humphreymburu then did it manually.

@pcambra we need to find a way to let the cluster website focal point enable those feature without the tricks or workaround that @humphreymburu was doing..

**Comment by pcambra** [comment]
So when adding a new cluster / bundle, there should be the following features enabled by default:  Contacts, Documents, Maps.
Is this correct?

**Comment by MartinMaritim** [comment]
@pcambra currently this is the case, the features are enabled by default. The issue is that the menu items(top horizontal menu) are not automatically created. 

To reproduce this issue:

1. Create a new cluster/bundle.
2. The horizontal top menu is not there by default.
3. To create the menu, go to the group's admin page, and click on 'Menu'.
4. Add a new menu item.
5. Repeat step 4 again if you don't see the menu table.
6. Go to the group's admin page and click on 'Features'.
7. De activate then activate the desired features eg Documents, Contacts etc.
8. The features menu items will now be available when you visit the Cluster/Space.

The desired functionality would be to have the enabled features menu items show by default.

**Comment by javedyousafzai** [comment]
correct @pcambra , those features should be there  'by default' when we add new bundle items i.e. cluster, sector or working group.
