### ISSUE TITLE
Change wording of locked contact lists

### ISSUE THREAD

**Issue by Yaelle01** [humanitarianresponse/site#129]
Hi @javedyousafzai , 

Craig asked us to change the wording of the locked country contact list interface for unverified users. Could you take a look at it and take action, please. Thank you, Yaelle 

FYI @andrejverity 

![hr_info_protected-list](https://cloud.githubusercontent.com/assets/13348894/10366082/29b7d28e-6dc8-11e5-8940-4e665b34ad87.JPG)

**Comment by javedyousafzai** [comment]
I am not sure If I have access to this page. I guess its a view. @MartinMaritim or @humphreymburu can you please take actions and remove the 'red' highlighted text (This setting is used in situations where those in-countries responders believe that their information should not be easily available due to security concerns. In this case, ) from the box?

thanks.

**Comment by javedyousafzai** [comment]
can we close this case?
