### ISSUE TITLE
Improve the organic groups top menu generation

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#241]
Currently we're relying on OG menu single (https://www.drupal.org/project/og_menu_single) for maintaining the top menu on the menu that appears on operations and clusters.

![nepal humanitarianresponse 2015-12-16 13-48-54](https://cloud.githubusercontent.com/assets/104912/11842481/c775dac0-a3fb-11e5-982c-9cc7fe45d85d.jpg)

For every feature, for every cluster, bundle, operation, we generate one menu link. This results in almos 20 thousand menu items generated automatically.

All these should be created as menu routes instead as they share most of their attributes. They would be regenerated consistently on cache clears and save db space. The menu links table has 23057 items and 19374 are generated this way and could be deleted.

Tradeoff: This will not allow users to create custom links on the top menu out of the box, we'd need to build an override system that would handle these links, and allow the users to enable/disable, change title and create new elements for this menu.

**Comment by guillaumev** [comment]
@emmajane @andrejverity the fix is working on staging, see for example: http://staging.hrinfo.568elmp02.blackmesh.com/en/operations/burundi. I just need to order the menu items the way they were before.

@Yaelle01 Could you get me a list of all the spaces which have custom menu items, see how big this list is ?

FYI, I would really like to get this fix in place, as it can be a quick win which can bring quite a substantial performance improvement

**Comment by Yaelle01** [comment]
@guillaumev, I've checked all active operational sites and the only ones off the norm are Colombia, Nepal and Yemen.

- Colombia: Does not use HID, therefore two 'Contacts' tabs show up - the one for HID should be disabled. 
- Nepal: Assessments is linked to a WG page. Please overwrite, it's outdated. 
- Yemen: Only site, which enabled the discussion board. Please overwrite, it's not being used. 

Two more questions: 

(1) What will happen to the translated menus (esp. Ukraine)?
(2) Will the global spaces be affected? 

Last observations: 

- In Ethiopia, the order of the tabs is off - I wonder why. 
- For most countries all features are enabled, even though I know they were turned off previously.

**Comment by guillaumev** [comment]
@Yaelle01 
* Colombia: will need to add some custom code for this
* Nepal: will be overwritten automatically then, nothing to do
* Yemen: if the discussion board is disabled, the menu won't show up anymore

1) Translated menus: I will double check, but I believe all that will be needed will be to retranslate them once, through the "Translate interface"
2) Yes, global spaces will be affected, so it would be good to check them one by one as well

* Ethiopia: will fix itself after the update
* Note that this update will require that a country has enabled only the features it needs (otherwise a menu item will show up), so we better make sure as well that each country and global space has enabled only the features it needs

**Comment by guillaumev** [comment]
@Yaelle01 Confirming that menus can be translated, see for example http://staging.hrinfo.568elmp02.blackmesh.com/ru/operations/ukraine, you will see that the Documents item is already translated, it will just be a matter of adding the translations of the other menu items in production.

**Comment by guillaumev** [comment]
@Yaelle01 Checking global spaces:

* Humanitarian Programme Cycle: currently, the main menu item is "HPC" instead of "Humanitarian Programme Cycle". It will be replaced by "Humanitarian Programme Cycle" after the update. Not sure that's an issue
* Not related to this case, but HIV/AIDS points to http://his.unhcr.org/aae/ which shows a database error
* Not related to this case, but Humanitarian/Military Dialogue points to this google site: https://sites.google.com/a/dialoguing.org/humanitarian-military-dialogue/ shouldn't we ask this team to move to HRinfo ?
* Shouldn't this be shut down and point to HDX ? https://www.humanitarianresponse.info/en/cod-services
* Same question with this: https://www.humanitarianresponse.info/en/applications/data
* Indicators registry: https://www.humanitarianresponse.info/en/applications/ir seems to have a custom horizontal menu, so will need to write some custom code

I believe the only remaining items before this can be put in production are the following:

1. Fix for the indicators registry (and eventually the HPC)
2. Make sure each space has enabled only the features it needs

**Comment by guillaumev** [comment]
@Yaelle01 the fix for the indicators registry is in place, and I checked each global space to make sure only the required feature are enabled. Global spaces are ready for the change. Let me know if I should look into each operational space as well.

**Comment by Yaelle01** [comment]
@guillaumev - all operations are reviewed and features that have no content or have not been updated for at least 6 months have been disabled. A lot of the 'enabled' features seem to have been enabled automatically through previous releases (e.g. Yemen having all features turned on even though I went through them with the team a few months ago).

**Comment by guillaumev** [comment]
This is now done, and og_menu_single has been disabled, uninstalled and removed from the code repository. Closing this.
