### ISSUE TITLE
Mitigate out of memory errors on groups

### ISSUE THREAD

**Issue by pcambra** [humanitarianresponse/site#283]
We have a memory error when accesing /group, look for ways to optimise this.

Example to test locally: http://www.hrinfo.vm/en/operations/colombia/group

**Comment by guillaumev** [comment]
Hi @pcambra,

I think this might be related (see my comment about performance issue):

https://www.drupal.org/node/2195269
and
https://github.com/humanitarianresponse/site/issues/254

I might be wrong, but I believe that adding the if(og_is_group) check to fix issue 254 caused the performance issues (and maybe the mysql issues) we are seeing now, because now Drupal has to load the entire node everytime...

**Comment by pcambra** [comment]
Using entity load instead of relying in the menu seems to help with the issue, see the PR above.

**Comment by emmajane** [comment]
Part of the extra-ordinary release on 13 January. Fixed the issue. Closing.
