### ISSUE TITLE
Notify user after adding to space

### ISSUE THREAD

**Issue by guillaumev** [humanitarianresponse/site#40]
Follow up from https://atrium.humanitarianresponse.info/humanitarian_response/node/4007

**Comment by guillaumev** [comment]
I just tested this. It works (at least for operations) but here are a few things that need to be improved:

1. Remove the inactive rules: rather than keeping them in the code and marking them as inactive, remove them completely
2. Write more meaningful emails: rather than "User Fullname, You are now a member of the group x located at [url]", write something like "Dear [user], [manager] added you to space X as a [manager|editor]. This means you can now perform administrative operations on space X. Best regards, The Humanitarianresponse.info team". I'm notifying @Yaelle01 to see if she has a better text for the emails.
3. Don't notify the group author: the group authors are usually either myself or Javed. This means we would get tons of emails when this gets into production. Therefore, just notify the added person.

**Comment by Yaelle01** [comment]
Here is the email text for adding a manager. However the 2nd part (i.e. the Google Apps service), will only apply for cluster IMOs, so you will somehow make the distinction.

Dear [firstname],
<empty line>
Welcome to the <name of the space> on the HumanitarianResponse.info platform in <name of the operation> ! 

<empty line>

We wanted to let you know that you are now a manager of the <name of the space> pages in <name of the operation>. 

<empty line>

As a manager you have entire control of your pages: You can design your pages as you wish, add documents, create new pages, etc. You can also add others as managers or editors. To give you some guidance on how to work with the platform, please check out https://www.humanitarianresponse.info/help . If you run into trouble, please contact the OCHA Information Management Officer in country or write to us at help@humanitarianresponse.info . 

<empty line>

You are also provided with a Google Apps account and are receiving two generic email accounts. In order to access them, just log in at www.gmail.com with the credential below:  

<empty line>
Email: <name of email 1> 	Password: <code>
Email: <name of email 2> 	Password: <code>
<empty line>

We hope you will enjoy the HR.info services! 

<empty line>

Your HR.info team <breakline>
Site: www.humanitarianresponse.info
Animation: https://youtu.be/OAzNjYtabuM
Twitter: https://twitter.com/humresponse

**Comment by humphreymburu** [comment]
@guillaumev About Google Apps Account and receiving the generic accounts.How will the managers get the email accounts and passwords .

**Comment by guillaumev** [comment]
@humphreymburu Do not worry about google apps for the moment, let's release a version of these notifications without google apps first...

**Comment by guillaumev** [comment]
@humphreymburu I merged this into the dev branch, but I'm not closing the issue, as the footer of the message appears like this: Your HR.info team Site: www.humanitarianresponse.info Animation:
https://youtu.be/OAzNjYtabuM Twitter: https://twitter.com/humresponse

Could you make it appear line by line, ie:
Your HR.info team
Site: www.humanitarianresponse.info
Animation: https://youtu.be/OAzNjYtabuM
Twitter: https://twitter.com/humresponse

**Comment by guillaumev** [comment]
Closing this.
