### ISSUE TITLE
 Contacts page on HR.info in Operational website

### ISSUE THREAD

**Issue by javedyousafzai** [humanitarianresponse/site#64]
**Challenge:**

When we are redirecting 'Contacts' in HR.info to Humanitarian ID, not all offices want to have the HID contacts directly displayed in HR.info. Therefore we need an interface to get people to login (or register first) before accessing the contacts.

Here's the design in GoogleDoc;: https://drive.google.com/folderview?id=0B4DjXe64lR7sfnlLZGViOUJBNG1KV0JxbHpCMVZKS1VmalBmQ0tuVHM2cUh1a3A4Y1kyQlU&usp=drive_web

**Suggested solution;**

Not sure how easy would it be to implement, but by default when the viewer click on the 'Contacts' in the horizontal menu, the following screen will display, and when they click on the 'Login' or Register' button, they will see the contacts on the Contacts page within HR.info just like we do for [Nepal] (https://www.humanitarianresponse.info/en/operations/nepal/hid_contacts#table/1) and [Philippines] (https://www.humanitarianresponse.info/en/operations/philippines/hid_contacts#table/1)

![image](https://cloud.githubusercontent.com/assets/3966785/9493282/db4d3296-4bfe-11e5-8fbc-5450d0096e71.png)

If there are better suggestions/solution, please add them here;

**Comment by Yaelle01** [comment]
Yemen is starting to roll Humanitarian ID out tomorrow. Any estimates on when the above could be implemented? @javedyousafzai @pcambra

**Comment by Yaelle01** [comment]
Let me try and flesh it out a bit more:

1. User registered on Humanitarian ID and checked in to Yemen: 
Login leads directly to the contact list in HR.info

2. User registered on Humanitarian ID but NOT checked in to Yemen: 
Login leads to dashboard in Humanitarian ID. User would need to check in to Yemen at this point. 

3. User registered on Humanitarian ID as a verified user:
Login leads directly to the contact list in HR.info

4. User not registered on Humanitarian ID
Click onto register, will lead to auth_client_hid. User needs to register and check into Yemen. 

@andrejverity - correct?

**Comment by pcambra** [comment]
Acceptance criteria (To be confirmed):

* When I'm not logged in, clicking on contacts will display the login/register screen as the designs.
* When clicking on login/register, I'm redirected to the HID website and after logging in, I'm redirected to the contacts page.
* When I am logged in, but you haven't checked in, I get redirected to my dashboard

Open questions:

* We need the original designs (psd) for reference (Ignacio)
* We need a way to make the contacts tab for organisations visible only for the relevant users.
* What about the HID endpoint, for private contact organisations, this needs to be protected as well
* Clusters have contacts too, do we need privacy at that level too? meaning if we have a public contacts organisation, can they have private contacts settings for each of the clusters?

**Comment by andrejverity** [comment]
This seem to be a bit extra complicated.

A couple scenarios as I see them:

1) HID is set as private for a given Operation   (this is set on HR.info)

a) When a user is logged into HR.info (using HID account) and they go to the contacts page:
 i) if they are a verified user on HID, they see the full contact list
 ii) if they are NOT a verified user on HID, they do not see any contacts except themselves.

b) When a user is not logged into HR.info and they go to the contacts page:
 i) they see the Login/Register page that Ignacio designed.

2) HID is set as "Open" for a given operation (or whatever it is called on HR.info)
  -- regardless if the user is logged into HR.info or not, they see the full contact list.

THEREFORE, there should not be any re-directs to HID (except to Login for HR.info).

ALSO: there is no need to be checked into Yemen in order to see the contacts.

**Comment by guillaumev** [comment]
I implemented the logic (without the design) here: https://github.com/humanitarianresponse/site/commit/bd79db84d9cb48c6b0319c4b072896efb66540f3.

@andrejverity currently, in the case of hid being set to private and a user logged in but not verified, it shows a message saying "In order to see this list, you need to be a verified user in Humanitarian ID". Any reason why you want to show the contact details of just this single user ? I think it would make more sense to display a message explaining why the user can't see the list rather than showing just their profile...

**Comment by pcambra** [comment]
We need to handle also the security bits on the resources themselves.
This hrinfo json will be available even if the listing in the site is restricted, so we need to restrict this

https://www.humanitarianresponse.info/hid/proxy?api_path=v0/contact/view&locationId=hrinfo:82&status=1&type=local

And also the source on HID would be public, and that's a fix we need to discuss with the hid team

http://profiles.humanitarian.id/v0/contact/view?locationId=hrinfo%3A82&status=1&type=local&q=hid/proxy&_access_client_id=hrinfo-prod&_access_key=33010e323b0588fdda7d8117880c9b887e10a3011e8ee734e934b83b560dbf4f

**Comment by andrejverity** [comment]
@guillaumev that is fine, but we should get a nice "phrase" from @Yaelle01 

@Yaelle01 can you perhaps ask Ignacio for a nice "design" of this empty contacts page with that message on it?

**Comment by pcambra** [comment]
I'm about to push a change for this, I've got these provisional messages, @Yaelle01 could you send me better ones? :)

"Your account hasn\'t been verified yet. Please wait or contact the operation responsible for more information." -> This will be displayed when a non verified user accesses a private contact list. 

"You can't access the contact list for this operation" -> This one is a generic message in case there's a use case we haven't anticipated.

**Comment by Yaelle01** [comment]
Hi @pcambra , I changed the text on HID slightly. I think it is also valid for HR.info. Not sure if we need also a generic message in this case. But please let me know if I am missing out on something. "This contact list has been set as private by our field-level administrators. This setting is used in situations where those in-countries responders believe that their information should not be easily available due to security concerns. In this case, only "verified" Humanitarian ID users can access the contact list. For information about "verified" users, please see our FAQs.(http://humanitarian.id) and contact us at info@humanitarian.id ."

**Comment by Yaelle01** [comment]
@andrejverity - I also don't understand (see Guillaume's comment) why a contact should only see him/herself when not verified

**Comment by pcambra** [comment]
We're not doing that because of limitations on the HID API, there will be a message displayed only.

**Comment by pcambra** [comment]
@javedyousafzai can we close this one?

**Comment by javedyousafzai** [comment]
let me do a quick test after our meeting and then I will close it.

**Comment by javedyousafzai** [comment]
can we close this case?

**Comment by pcambra** [comment]
@javedyousafzai you tell me?

**Comment by javedyousafzai** [comment]
OK I am closing this case after confirming from @Yaelle01.
